android {
    signingConfigs {
        release {
            storeFile = file("upload-keystore.jks")
            storePassword = System.getenv("STORE_PWD")
            keyAlias = System.getenv("KEY_ALIAS")
            keyPassword = System.getenv("KEY_PWD")
        }
    }
    buildTypes {
        release {
            signingConfig = signingConfigs.release
            minifyEnabled = true
            shrinkResources = true
        }
    }
}
